"""add trusted_domains

Revision ID: 284804dd79d5
Revises: 98edb45f7bfc
Create Date: 2026-08-27 10:31:43.423528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284804dd79d5'
down_revision = '98edb45f7bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trusted_domains')
    # ### end Alembic commands ###
