"""add content_rules and flagged_mails

Revision ID: 98edb45f7bfc
Revises: 3e51f89d3f32
Create Date: 2026-08-26 17:10:30.312007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98edb45f7bfc'
down_revision = '3e51f89d3f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=300), nullable=False),
    sa.Column('rule_type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flagged_mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('mail_body', sa.Text(), nullable=False),
    sa.Column('matched_category', sa.String(length=30), nullable=False),
    sa.Column('matched_rule_source', sa.String(length=10), nullable=False),
    sa.Column('matched_rule_id', sa.Integer(), nullable=True),
    sa.Column('matched_pattern', sa.String(length=300), nullable=True),
    sa.Column('matched_snippet', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flagged_mails')
    op.drop_table('content_rules')
    # ### end Alembic commands ###
